chef-cookbooks/audit

- libraries/profile.rb
- metadata.rb
File rename won't work across devices, throwing an "Invalid cross-device link" exception.
Thanks Marcus for reporting the issue!
> Use move to avoid cross-device error

- attributes/default.rb
- libraries/profile.rb
- libraries/report.rb
While testing I noticed a couple of scenarios:
1. A client with a time/date skew simply getting a "401 Unauthorized" error while attempting to download profiles failing the converge.
2. A client failing to converge if the Compliance server API was unavailable.
These changes give the ability to handle these exceptions and allow the node to still continue with the rest of the converge.
> adding ability to handle offline compliance server

- attributes/default.rb
- libraries/report.rb
Simple implementation of #3 
Fails converge _after_ the report submission if there are any audit failures.
> failing converge if any audits failed

- libraries/profile.rb
There was an issue with inspec gem causing TypeError
```
================================================================================
Error executing action `execute` on resource 'compliance_profile[linux]'
================================================================================
TypeError
---------
no implicit conversion of Symbol into Integer
```
It was fixed here: https://github.com/chef/inspec/pull/679
https://github.com/chef/inspec/pull/679
The new gem version (0.19.3) was released here: https://github.com/chef/inspec/pull/680
Tested converging the audit cookbook with inspec v0.19.3 and the issue is resolved.
> update inspec gem version pin

- README.md
Chef client < 12.5.1 is not able to use the newer `use_automatic_resource_name` method:
```
NameError
---------
undefined local variable or method `use_automatic_resource_name' for ComplianceProfile:Class
```
This change simply documents the client version required to utilized the new custom resource method.
> update README.md with client version requirement

- libraries/profile.rb
- libraries/report.rb
When using the token and communicating directly with the Compliance Server one will encounter this error:
```
IOError
-------
use_ssl value changed, but session already started
```
This change fixes the above error by setting the use_ssl options within the Net::HTTP.start() method, not afterwards.
> fix: use_ssl value has changed error

- libraries/matchers.rb
- metadata.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
Give a more descriptive error message if the profile name provided is invalid:
```bash
RuntimeError
------------
Invalid profile name 'mylinux'. Must contain /, e.g. 'john/ssh'
```
Adds unit tests for this case, but also for correct profile names
> Add profile name validation and unit tests

- attributes/default.rb
- libraries/profile.rb
- libraries/report.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
This changes the default behavior for inspec during the node converge by suppressing the scan result json report from STDOUT.  Various customers have remarked that the default scan results being dumped to STDOUT is too busy and clutters up the converge output. Users can choose to continue to get the json report output by toggling the attribute: `default['audit']['quiet'] = false`.  The default value is `true`.  When, set to `true`, a short scan result Summary for each profile is output when the `compliance_report` is executed. 
N/A
> quiet mode for inspec scans

- README.md
- libraries/helper.rb
- libraries/profile.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
This implementation provides the ability to execute audit profiles from various additional sources, relying on existing plugin capabilities of the inspec gem.
Specifically, these sources are now supported:
* Supermarket
* Local filesystem path
* Github repo
#49
> Support other sources

- libraries/profile.rb
This change copies instead of moving, due to an Windows access error
#48 
Checked using test-kitchen against Ubuntu and Windows
> changed FileUtils, tar_path and profile_path behavior

- .kitchen.yml
- README.md
- attributes/default.rb
- libraries/helper.rb
- libraries/profile.rb
- libraries/report.rb
- metadata.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
This PR improves the support for direct reporting to Chef Compliance
fixes #45
fixes #52
> Optimize the direct reporting to Chef Compliance

- attributes/default.rb
- libraries/helper.rb
- metadata.rb
When the token is not set correctly, the audit cookbook is returning weird errors:
```
Starting Chef Client, version 12.10.24
resolving cookbooks for run list: ["audit"]
Synchronizing Cookbooks:
- audit (0.9.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: audit::default
* compliance_profile[linux] action fetch
* chef_gem[inspec] action install
- install version 0.22.1 of package inspec
[2016-06-01T13:06:49-07:00] WARN: Using inspec version: (0.22.1)
- install/update inspec
* directory[/var/chef/cache/compliance] action create
- create new directory /var/chef/cache/compliance
- create cache directory
- fetch compliance profile
* chef_gem[inspec] action install (up to date)
* directory[/var/chef/cache/compliance] action create (up to date)
* …
```
> handle auth error

- libraries/helper.rb
- libraries/profile.rb
- libraries/report.rb
This change resolves the following error from version 0.10.0 of the cookbook:
```
NoMethodError
-------------
undefined method `code' for #<Tempfile:/tmp/compliance-profile20160609-2220-117sw6.tgz>
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/audit/libraries/helper.rb:40:in `with_http_rescue'
/var/chef/cache/cookbooks/audit/libraries/profile.rb:93:in `block (2 levels) in <class:ComplianceProfile>'
/var/chef/cache/cookbooks/audit/libraries/profile.rb:54:in `block in <class:ComplianceProfile>'
```
It also re-adds the `with_http_rescue` method call for proper error handling when communicating with chef_gate on the Chef Server.  It's very beneficial to have this error handling.
The `with_http_rescue` method was removed in between version 0.10.0 and 0.11.0 of the cookbook.
This …
> adding with_http_rescue method call back in

- libraries/report.rb
This fixes a bug I was having where the code was using a non-standard way of accessing node attributes. Once I changed it back I no longer got the error.
I didn't fill out this as an issue, just fixed it.
> Standardized node access to classic way

- libraries/report.rb
This change removes the requirement for setting the `['audit']['server']` attribute when collector is set to `chef-server`.  If `server` is not set, then the Chef Server url will be determined by what's in the `client.rb` file.  This allows for an easier Global Chef architecture where there are regional Chef Servers - the audit cookbook can just pick up the server url from it’s client config without having to take into account regional attribute overrides.
Verification via pry when `['audit']['server']` is not set:
```
* compliance_report[chef-server] action execute[2016-08-04T16:12:02+00:00] INFO: Summary for linux {"duration":0.621066652,"example_count":45,"failure_count":28,"skip_count":0}
Frame number: 0/36
From: /var/chef/cache/cookbooks/audit/libraries/report.rb @ line 57 …
```
> removing requirement for setting chef server url

- .rubocop.yml
- CHANGELOG.md
- Rakefile
- tasks/changelog.rake
This updates the rake task for generating the CHANGELOG documentation so that it includes the new link as well as dynamically gets the current version number.
It solves an issue where the changelog `Full Changelog` link is generated wrong.
> Update changelog generator task to be native rake task

- libraries/collector_classes.rb
- libraries/helper.rb
- libraries/report.rb
- metadata.rb
Fixes the following two exceptions when using the ChefCompliance collector:
```
================================================================================
Error executing action `execute` on resource 'compliance_report[chef-server]'
================================================================================
NameError
---------
undefined local variable or method `blob' for #<Collector::ChefCompliance:0x00000005fbf040>
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/audit/libraries/collector_classes.rb:236:in `send_report'
/tmp/kitchen/cache/cookbooks/audit/libraries/report.rb:49:in `block (2 levels) in <class:ComplianceReport>'
/tmp/kitchen/cache/cookbooks/audit/libraries/report.rb:24:in `block in <class:ComplianceReport>'
```
and:
``` …
```
> ChefCompliance collector fix

- Gemfile
- Rakefile
- examples/kitchen/.kitchen.linux.yml
- examples/kitchen/.kitchen.win.yml
- libraries/compliance.rb
- libraries/helper.rb
- libraries/inspec.rb
- libraries/profile.rb
- libraries/report.rb
- recipes/_inspec.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
This PR is doing the following:
- extract inspec gem installation
- ensures the refresh token is only exchanged once
Customers reported that `refresh_token` handling was not working as expected and lead to authentication errors for some requests.
> improve compliance refresh token handling

- README.md
- TROUBLESHOOTING.md
- libraries/helper.rb
Clarify 401 Auth - bad clock error.
This change adds clarification to the HTTP 401/403 Authentication errors due to time skew between client and server.
> making Auth - bad clock errors clearer

- libraries/profile.rb
This PR fixes the call to `Tempfile.new`
Since Ruby 2.2.0 bundled in newer versions of chef-client, `Tempfile.new` errors with:
```
================================================================================
Error executing action `fetch` on resource 'compliance_profile[linux]'
================================================================================
ArgumentError
-------------
wrong number of arguments (given 3, expected 0..2)
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/audit/libraries/profile.rb:64:in `new'
```
This is because Tempfile.new has just ignored the 'wb+' option - not so any more.
https://bugs.ruby-lang.org/issues/10690
This PR fixes how the Tempfile object is instantiated.
As documented here: …
> fix Tempfile.new

- attributes/default.rb
- libraries/compliance.rb
Method `retrieve_access_token` is not providing any logging if it fails to get an access token. This provides misleading error messages like:
```
Recipe: audit::default
* ruby_block[exchange_refresh_token] action run
- execute the ruby block exchange_refresh_token
* directory[/tmp/kitchen/cache/compliance] action create (up to date)
* file[/tmp/kitchen/cache/compliance/apache] action nothing (skipped due to action :nothing)
* compliance_profile[apache] action fetch
- load required inspec modules
* directory[/tmp/kitchen/cache/compliance] action create (up to date)
- create cache directory[2016-09-05T12:42:06+00:00] ERROR: 404 "Not Found" (Net::HTTPServerException)
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!' …
```
> Improve logging and comments for attributes

- libraries/matchers.rb
- libraries/profile.rb
- libraries/report.rb
- libraries/token.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
This PR introduces `compliance_token` resource.
The goal is to have a self-contained resource for storing the Compliance Server token and exchanging the `refresh_token` for an access token, if needed.
The `compliance_token` resource stashes the token in Chef's `node.run_state` hash. The token can then be passed between resources, and evaluated during the execution phase. run_state is always discarded at the end of the chef-client run.
N/A
> Compliance Token resource

- attributes/default.rb
This is a simple change to bump the inspec version number the cookbook is pinned to.
https://github.com/chef-cookbooks/audit/issues/94
> bump inspec version to 0.34.0 to fix issue #94

- README.md
- attributes/default.rb
- libraries/compliance.rb
- libraries/matchers.rb
- libraries/profile.rb
- recipes/upload.rb
- spec/unit/recipes/upload_spec.rb
This PR provides action `upload` on resource `compliance_profile`
It replaces PR #92.
It uses inspec's `Compliance::API.upload()` and incorporates some error handling.
Only one mode is supported: direct communication with Compliance Server via token||refresh_token.
Usage is based on the audit hash like so:
```
default['audit']['server'] = 'https://compliance-server.test/api'
default['audit']['collector'] = 'chef-compliance'
default['audit']['token'] = nil
default['audit']['refresh_token'] = '20/cgm927J9371DRh8mZ2wp_bXRJxKPW52rtThkwQz5PzhBIcbq6VLB0LsdrfOXv_aBxprU1LTv3aUvHxe2mR-m2A=='
default['audit']['profiles'] = {
'admin/ssh2' => {
'source' => '/some/base_ssh.tar.gz'
},
'admin/linux2' => {
'source' => '/some/base_linux.tar.gz'
}
}
default['audit']['insecure'] = true
```
The goal is to …
> Compliance profile upload

- CHANGELOG.md
- metadata.rb
Due to the release of inspec version `1.0.0` and changes in the json formatter, we are bumping the audit cookbook to version `1.0.0`
The `['audit']['inspec_version']` cookbook attribute is also defaulting to `1.0.0` now.
> Release version 1.0.0

- attributes/default.rb
- libraries/compliance.rb
- libraries/report.rb
- metadata.rb
* This uses the new method to retrieve access tokens from InSpec plugin
* Fixes null pointer exception when calculating total failed controls
> Use the new method to retrieve access tokens and fix total_failed bug

- attributes/default.rb
- libraries/report.rb
- metadata.rb
`total_failed` only worked for `json-min` format. The current version was not working on Chef Visibility reporting.
> Fix bug when counting total failed controls in json format

- recipes/default.rb
- spec/unit/recipes/default_spec.rb
There were some problems when using `interval`:
1.  profiles fetched but not executed
2. report always sent, even if profile not executed
This fixes: #101 and #102 
> fixing interval issues

- README.md
There is some mis-understanding about using the `refresh_token`.  Hopefully this clears up some confusion.
N/A
> described refresh_token behavior when logging out of UI

- .kitchen.vagrant.yml
- .travis.yml
- Rakefile
this PR adds chef-client runs via travis
> Activate test-kitchen in travis

- README.md
Since we work on 2.x on master, customers need to know that this doc is not working for 1.x branch.
> add reference to 1.x documentation

- .kitchen.yml
- Berksfile
- README.md
- examples/kitchen/.kitchen.linux.yml
- examples/kitchen/.kitchen.win.yml
- files/default/audit_report.rb
- libraries/helper.rb
- recipes/prep.rb
fixes: https://github.com/chef-cookbooks/audit/issues/118
unsure about the disabled part, looking into that to confirm that works..
>  harmonize profile targets

- .kitchen.yml
- Berksfile
- recipes/prep.rb
addresses issues from https://github.com/chef-cookbooks/audit/pull/121
i think?  is this what you meant @jeremymv2 @chris-rock ??
> move testing deps to integration group in berksfile

- examples/profile_upload/.kitchen.yml
- examples/profile_upload/Berksfile
- examples/profile_upload/README.md
- examples/profile_upload/metadata.rb
- examples/profile_upload/recipes/default.rb
- libraries/compliance.rb
- libraries/helper.rb
- recipes/default.rb
- recipes/upload.rb
- resources/inspec.rb
- resources/upload.rb
tada!  it works  @chris-rock  .....i have a bunch of requires in the inspec resource....not sure how to get around that?
using this to test it: https://github.com/vjeffrey/testing-audit
> Upload profiles to Chef Compliance via Chef resource

- README.md
- files/default/audit_report.rb
- libraries/helper.rb
- spec/unit/report/default_spec.rb
Bring back intervals!
** working on unit test
> bring back intervals

- files/default/audit_report.rb
- libraries/helper.rb
- libraries/matchers.rb
- spec/unit/libraries/compliance_spec.rb
- spec/unit/libraries/helpers_spec.rb
- spec/unit/libraries/visibility_spec.rb
- spec/unit/recipes/default_spec.rb
- spec/unit/recipes/upload_spec.rb
- spec/unit/report/audit_report_spec.rb
This commit adds more testing!
A few of them I couldn't get to work correctly....
> Add unit tests

- .gitignore
- .rubocop.yml
- attributes/default.rb
- examples/chef-server/README.md
- examples/chef-server/Vagrantfile
- examples/compliance/README.md
- files/default/audit_report.rb
- files/default/vendor/chef-server/fetcher.rb
- libraries/collector_classes.rb
- libraries/helper.rb
- spec/unit/report/audit_report_spec.rb
> implement chef-server fetcher and reporter

- attributes/default.rb
- files/default/handler/audit_report.rb
This allows users to enable the chef-server fetcher with another reporter, e.g. Visibility
Just set the attribute `default['audit']['fetcher'] = 'chef-server'`
> enable chef-server fetcher attribute

- README.md
- attributes/default.rb
- recipes/default.rb
- recipes/upload.rb
- spec/unit/recipes/default_spec.rb
This allows for sourcing the `inspec` gem from alternate location other than rubygems.org
related to #112 
> adding support for alternate gem source

- recipes/inspec.rb
- recipes/upload.rb
Isolate the `inspec` resource to its own recipe so that it's declared only once.
n/a
> dry up chef_gem inspec resource declarations

- files/default/handler/audit_report.rb
Change error message for interval timing to warn message with better wording.
Move creation of timestamp file below the check_interval_settings check to ensure the user can run through the audit cookbook successfully the first time around when interval settings are enabled
fixes https://github.com/chef-cookbooks/audit/issues/149
> change interval timing msg to warn

- README.md
- files/default/handler/audit_report.rb
- libraries/collector_classes.rb
- spec/unit/libraries/visibility_spec.rb
This adds support for `node['audit']['insecure']` to the Chef Visibility collector
#150
> Add insecure flag for `Collector::ChefVisibility`

- README.md
The link in this PR requires this to be merged:
https://github.com/chef/chef-web-docs/pull/254
> Mention the integration guide between Chef Server and Automate

- .rubocop.yml
- README.md
- attributes/default.rb
- examples/chef-server/Vagrantfile
- examples/wrapper_audit/recipes/default.rb
- files/default/handler/audit_report.rb
- files/default/vendor/chef-server/fetcher.rb
- libraries/helper.rb
- metadata.rb
Fixes https://github.com/chef-cookbooks/audit/issues/158
The chef-server fetcher is also using a different fetching URL when reporter chef-server-visibility is used.
I was also thinking to introduce replace the current `chef-server` fetcher with `chef-server-compliance` and possibly add a `chef-server-automate` reporter. In the interest of keeping this change small for now. I reverted the fetcher change.
Attributes and README are not fully updated. Waiting for 👍  before doing that.
> Update fetcher for chef-server-visibility and add chef-server-compliance collector

- files/default/handler/audit_report.rb
- spec/unit/libraries/json_file_spec.rb
Changes timestamp format so that filename does not contain colon which causes errors on Windows.
```
irb(main):027:0> "inspec-#{Time.now.strftime('%Y%m%d%H%M%S')}.json"
=> "inspec-20161202230551.json"
irb(main):028:0>
```
https://github.com/chef-cookbooks/audit/issues/173
> change json-file filename

- attributes/default.rb
There are a lot of tunables in the attribute file.
Attempting to clean up and add clarifications.
N/A
> Attributes file clarifications

- README.md
For the `chef-server-visibility` collector, a minimum chef-client version 12.16.42 is required.  See: "Configure the Data Collector Automatically" https://github.com/chef/chef/blob/master/CHANGELOG.md#v121642-2016-11-04
Also, just fixed up one of the example attribute blocks that contained mixed ruby/json syntax.
N/A
> min chef-client version for chef-server-visibility

- .kitchen.yml
- .travis.yml
- files/default/handler/audit_report.rb
This enables user to fail a chef-client run, if a some parts fail during reporting stage
fixes #166 
Thank you @stevendanna for highlighting the solution
> throw chef-client exception if requested by users

- README.md
Docs improvement after helping a person in the community figure out why profiles could not be downloaded from the profiles API.
User was under the impression that profile `base/windows` was being shipped by default with Chef Automate.
> Mention uploading profiles to Automate

- files/default/vendor/chef-server/fetcher.rb
- libraries/helper.rb
- spec/unit/report/fetcher_spec.rb
This allows `chef-server-visibility` collector + `chef-server` fetcher to work as desired.
#184 
> fixing #184

- .travis.yml
Automate integration tests do not run for external PRs. Therefore we should make them optional.
> make automate integration tests optional

- libraries/helper.rb
- spec/spec_helper.rb
- spec/unit/libraries/helpers_spec.rb
This solves an issue where the chef-client cookbook cleanup step removes the report_timing.json file from the cache.  Upon looking into chef client you can see the following:
https://github.com/chef/chef/blob/master/lib/chef/cookbook/synchronizer.rb#L184-L195
https://github.com/chef/chef/blob/master/lib/chef/policy_builder/expand_node_object.rb#L219-L223
And upon setting the logs to info and running chef client you can see the following:
```
[2017-01-04T23:01:25+00:00] INFO: Removing cookbooks/audit/report_timing.json from the cache; it is no longer needed by chef-client.
```
This resolves the issue by putting the file in the chef cache directory specified by chef-client under a compliance folder.  
N/A
> Fix issue with interval being removed because of chef-client cookbook cleanup

- Gemfile
- README.md
- libraries/collector_classes.rb
- spec/data/mock.rb
- spec/unit/libraries/compliance_spec.rb
- spec/unit/libraries/visibility_spec.rb
Some document stores like ElasticSearch don't like values that change type. This change converts all profile attribute defaults to string and adds a 'type' key to store the original type.
Some testing improvements.
> Type the inspec profile attributes

- README.md
Modify `README.md` to reference the `chef-server-compliance` collector change introduced [here](https://github.com/chef-cookbooks/audit/commit/92f0601c70a5f8013f22c081203be98768e8ceb1).
> Use `chef-server-compliance` vs `chef-server`

- .kitchen.yml
- .travis.yml
- README.md
- attributes/default.rb
- libraries/matchers.rb
- metadata.rb
- recipes/inspec.rb
- resources/inspec_gem.rb
- spec/unit/recipes/default_spec.rb
- test/cookbooks/test_helper/recipes/install_inspec_1_17.rb
- test/integration/default/default_spec.rb
- test/integration/gem-install-version/default_spec.rb
To assist with air-gapped installations, the audit cookbook is
being modified to only install InSpec if it's not already installed
or if the user has explicitly stated a version to be installed.
This will allow users to use other methods of installing the gem
in the chef gem path, or take advantage of InSpec being included
in chef client in the future.
> Only install InSpec if not installed or version provided

- files/default/handler/audit_report.rb
- prints installed InSpec version
- improves the error message if profiles could not be fetched
- removes stacktrace if profile fetching went wrong
> better error output

- files/default/handler/audit_report.rb
- libraries/reporters/compliance.rb
- libraries/reporters/cs_compliance.rb
- spec/unit/libraries/compliance_spec.rb
- spec/unit/libraries/cs_compliance_spec.rb
- spec/unit/report/audit_report_spec.rb
This will run inspec just once, no matter if the report needs to be done in full json or min json.
* #206
* #155
* #38
> Always use json format for inspec report

- libraries/reporters/automate.rb
- spec/unit/libraries/automate_spec.rb
- spec/unit/libraries/cs_automate_spec.rb
Those types are not required with latest Automate 0.8.0
> Remove typed_attributes and leave the backend handle attributes

- files/default/handler/audit_report.rb
- files/default/vendor/chef-automate/fetcher.rb
- libraries/compliance.rb
> add automate fetcher for chef solo

- recipes/default.rb
- spec/unit/recipes/default_spec.rb
Chef's Audit Mode and InSpec (via the audit cookbook) are not compatible to be run simultaneously. This change raises an exception if the audit cookbook is attempted to be run on a node on which Chef's Audit mode is not disabled.
> Fail Chef run if Audit Mode is enabled

- libraries/reporters/json_file.rb
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
Make json-file reporter save JSON content instead of a ruby hash.
Fixes issue https://github.com/chef-cookbooks/audit/issues/244
> Make json-file reporter save JSON content

- files/default/vendor/chef-automate/fetcher.rb
The chef-automate fetcher uses the data_collector token settings but does not check to ensure it's set before passing it to InSpec for Fetcher purposes. This causes InSpec to create a data-collector-token header with a nil value, and then Net::HTTP will toss an ugly error when trying to call `#strip` on nil.
InSpec should validate inputs too, but this will help catch this issue in the audit cookbook and provide a better error message. This was found in the Chef sales demo environments.
> Raise exception if no token is set when using the chef-automate fetcher

- .kitchen.yml
- files/default/handler/audit_report.rb
- test/integration/gem-install-version/default.rb
- test/integration/skip-inspec-gem-install/default.rb
With the cookbook no longer specifying an inspec_version in attributes, it's important to ensure a compatible inspec is used.
I'm tempted to bump the required version to at least `1.25.0` because of this: https://github.com/chef/inspec/pull/1816
or should I make it 1.26 or 1.27?
> Ensure min version of inspec is used

- files/default/vendor/chef-server/fetcher.rb
- libraries/compliance.rb
- libraries/reporters/compliance.rb
- metadata.rb
- resources/compliance_upload.rb
Version 4 was not able to fetch profiles and report back to Chef Compliance. This PR fixes this.
This raises the general issue that we need to work even harder to consolidate the implementations between audit cookbook and inspec. This is tracked in #242
> fix chef compliance profile handling

- files/default/vendor/chef-automate/fetcher.rb
Signed-off-by: Nick Rycar <rycar@chef.io>
While specifying a workflow enterprise is not required to fetch compliance profiles from Chef Automate, inspec's validations do require that the associated header have a non-null value. Have updated the associated fetcher to seed the arbitrary value "default" into the enterprise header, and confirmed this produces the expected results in my local testing environment.
Fixes #258
- [N/A ] New functionality includes testing.
- [N/A ] New functionality has been documented in the README if applicable
> Non-null header value required for using chef-automate fetcher (#258)

- resources/inspec_gem.rb
The `clear_sources` property does not remove the default gem source when the RubyGems package provider does its work. We need to also set the `include_default_source` property to false to ensure users' requesting gem source is the only gem source used (instead of rubygems.org, for example).
> Disable default source when using user-supplied gem source

- .kitchen.yml
- Gemfile
- README.md
- attributes/default.rb
- files/default/handler/audit_report.rb
- spec/unit/report/audit_report_spec.rb
- test/cookbooks/test_helper/recipes/create_file.rb
- test/cookbooks/test_helper/recipes/setup.rb
- test/integration/attributes-work/default.rb
Fixes #261 
Allows for `node['audit']['attributes']` to define which attributes are passed into the InSpec run
Added documentation in `README.md`
Tested in kitchen, which relies on the [attributes-file-exists-profile](https://github.com/mhedgpeth/attribute-file-exists-profile) for testing that a file exists, driven off of an attribute.
@jeremymv2 this is what we were talking about as a better way to manage the "profile that rules them all" pattern.
> Support for attributes within audit cookbook

- .kitchen.yml
- .travis.yml
- test/integration/attributes-work/default.rb
- test/integration/inspec-attributes/default.rb
The work introduced by #262 was lacking an integration test for Test Kitchen. I also renamed the suite to be clearer about what it does and to avoid any confusion that the work may be a work-in-progress.
> Add test for InSpec Attributes functionality

- README.md
- test/integration/default/default.rb
Add the location of the json-file output to the README so people don't
have to go a-huntin' through the code to find the location.
Also fix a test that's failing in Travis due to the InSpec version being embedded in Chef omnibus since Chef 13.
Fixes #269
> Add json-file location to README

- .kitchen.yml
- README.md
- files/default/handler/audit_report.rb
- test/integration/inspec-attributes/default.rb
Providing the Chef node object (attributes, environment, etc.) to InSpec as an attribute will allow the ability to write more flexible profiles and eliminate the need for users to write out JSON files during the converge phase only to get read in by the profile later.
Fixes #268
> Pass Chef node to InSpec as an attribute

- .kitchen.yml
- .travis.yml
- README.md
- attributes/default.rb
- files/default/handler/audit_report.rb
- test/integration/chef-node-disabled/default.rb
- test/integration/chef-node-enabled/default.rb
- test/integration/inspec-attributes/default.rb
To encourage good practices, and to not send data to the InSpec runner that is not needed by most users, the `chef_node` attribute that contains the Chef node object hash will only be sent if the "chef_node_attribute_enabled" audit attribute is set to `true`
> Make chef_node attribute an opt-in feature

- libraries/compliance.rb
- libraries/reporters/automate.rb
- resources/inspec_gem.rb
The inspec_gem resource was triggering namespace collision deprecation warnings. This commit fixes those and also fixes an incorrect log severity level.
> Fix Chef deprecation warnings in inspec_gem resource

- files/default/handler/audit_report.rb
this log message should not be a warning
fixes https://github.com/chef-cookbooks/audit/issues/277
> The "Format is" log message should debug level

- files/default/vendor/chef-server/fetcher.rb
Signed-off-by: Kevin Reedy<kreedy@chef.io>
When an Automate user has an `@` in their username (like in LDAP or SAML), the profile URL to fetch is incorrect. It is currently resolving to `https://chefserver.example.com/compliance/organizations/acme/owners/example.com/compliance/cis-windows2012r2-level1-memberserver/tar` instead of `https://chefserver.example.com/compliance/organizations/acme/owners/First.Last@example.com/compliance/cis-windows2012r2-level1-memberserver/tar` for example.
I went to add new tests, but am confused by the current ones in https://github.com/chef-cookbooks/audit/blob/master/spec/unit/report/fetcher_spec.rb#L33-L37. I'd love to pair with someone Wednesday or early next week on the tests.
https://getchef.zendesk.com/agent/tickets/16346 …
> Handle '@' in username when grabbing compliance profiles

- libraries/reporters/automate.rb
- spec/unit/libraries/automate_spec.rb
- spec/unit/libraries/cs_automate_spec.rb
Signed-off-by: Alex Pop <apop@chef.io>
> Send end_time as utc RFC3339

- libraries/helper.rb
Run audits on CCR fail.
Fixes #289
> Include handler in exception handlers as well as report handlers

- attributes/default.rb
- files/default/handler/audit_report.rb
- metadata.rb
- spec/unit/report/audit_report_spec.rb
Add inspec caching attribute which defaults to true. This enables the new inspec caching when used by the Audit cookbook.
Fixes https://github.com/chef-cookbooks/audit/issues/296
> Enable Inspec caching

- README.md
- TROUBLESHOOTING.md
- libraries/reporters/automate.rb
- libraries/reporters/compliance.rb
- libraries/reporters/cs_automate.rb
- libraries/reporters/cs_compliance.rb
- metadata.rb
Log the size of the report if it reaches sizes that might cause problems.
Document the limits.
> Update reporters to log report size. Update readme

- README.md
- metadata.rb
Simply adding `supports 'aix'` to the cookbook's `metadata.rb` and some notes in the `README.md` clarifying the nature of AIX support.
N/A
> AIX support notes

- README.md
- files/default/vendor/chef-automate/fetcher.rb
- files/default/vendor/chef-server/fetcher.rb
- spec/unit/report/fetcher_spec.rb
This change allows a user to specify what version of an InSpec profile to pull from the Compliance store in Automate when using the audit cookbook.
There aren't any GitHub issues, but at least two customers have requested this functionality.
> Add optional version parameter when using Compliance store

- README.md
An error is now raised if you used the audit cookbook and audit mode is not disabled in the Chef client. This adds a note on how to disable audit mode.
https://github.com/chef-cookbooks/audit/commit/e41d0e99ad5da3e353e9fe167705bdd353b22aa3
> Update the readme regarding audit mode

- .kitchen.yml
- Gemfile
- resources/inspec_gem.rb
- test/integration/chef-node-disabled/default.rb
- test/integration/chef-node-enabled/default.rb
- test/integration/inspec-attributes/default.rb
This fixes the resource version issue with ChefClient 14.
Fixes https://github.com/chef-cookbooks/audit/issues/312
> Update Audit cookbook to support ChefClient 14

- CHANGELOG.md
- metadata.rb
> Bump audit to 6.1.0.

- CHANGELOG.md
- metadata.rb
Due to the removal of `compat_resource` and the move to `inspec-core` we are doing a major bump of the cookbook.
> Bump audit major version

- files/default/vendor/chef-server/fetcher.rb
- spec/unit/report/fetcher_spec.rb
Fix `nil class` error when profile not found on automate server.
As per issue: https://github.com/chef-cookbooks/audit/issues/301
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
> [MSYS-829] Fix nil class error when profile not found on automate server

- .kitchen.vagrant.yml
- .kitchen.yml
- .travis.yml
- README.md
- files/default/handler/audit_report.rb
Policyfiles with includes do not allow merging arrays and it's a bit unclear why an array was chosen. This patch does not change the existing behavior, only supplements it.
Signed-off-by: Matt Ray <matthewhray@gmail.com>
> Add support for node['audit']['profiles'] as a hash of hashes 

- files/default/handler/audit_report.rb
- metadata.rb
The new `json-automate` reporter fixes a few bugs when inherited profiles are used. Released last week with inspec `v2.2.64`
> Switch to the new json-automate reporter when inspec version allows it

- files/default/handler/audit_report.rb
- metadata.rb
In prep for the inspec 3.0 release which deprecates format.
> Switch format to reporter

- README.md
- attributes/default.rb
- files/default/handler/audit_report.rb
Signed-off-by: Joe Nuspl <nuspl@nvwls.com>
Add `node['audit']['json_file']['location']` to specify the json-file output location
https://github.com/chef-cookbooks/audit/issues/286
> Allow json-file output location to be configured

- README.md
InSpec version attribute should have an underscore, not a dash, in the README.
Signed-off-by: Gavin Reynolds <gavin@chef.io>
> Fix errant dash instead of underscore in example of InSpec version 

- .travis.yml
- Gemfile
I noticed a Travis failure on Ruby 2.2 on https://github.com/chef-cookbooks/audit/pull/340
But Ruby 2.2 was EOL six months ago: https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/
Chef 12 shipped with Ruby 2.1.2+ per https://github.com/chef/chef-rfc/blob/master/rfc015-chef-12.md#chef-12-1
Chef 12.14.11+ shipped with Ruby 2.3.1: https://github.com/chef/chef/commit/505a2baac3039b21ceb3fd815ccaeeba0321d1d8
Chef 14.0.1+ shipped with Ruby 2.4+: https://github.com/chef/chef/commit/aad8ccf126
We haven't shipped Ruby < 2.3 since 12.14 around August 2016.
> Remove Ruby 2.2 support

- resources/inspec_gem.rb
Set the `compile_time` flag on the inspec gem install to remove warnings in chef 14.
Fixes https://github.com/chef-cookbooks/audit/issues/342
> Add compile_time flag to inspec install.

- README.md
Signed-off-by: Shaun Mouton <smouton@chef.io>
fixes a broken link documenting how to add a self-signed Automate certificate to the /etc/chef/trusted_certs directory on clients
n/a
> Fixing broken link to data collection docs

- recipes/default.rb
Audit mode isn't a thing in Chef 15 so the config we're checking here
doesn't exist.
Signed-off-by: Tim Smith <tsmith@chef.io>
> Prevent failures when running on Chef 15

- .kitchen.yml
- .travis.yml
- Gemfile
- Rakefile
- test/integration/chef-node-disabled/default.rb
- test/integration/chef-node-enabled/default.rb
- test/integration/inspec-attributes/default.rb
Update to the latest `kitchen-dokken` driver so we can ensure that we are always pulling the latest chef image, see: someara/kitchen-dokken#181.  This makes running tests locally much more consistent.
Switch to using ChefDK in Travis so we can properly handle Chef-15 license acceptance.
This aligns the Travis testing to be handled similarly to what is in `chef-cookbooks/chef-client`
> Update to kitchen-dokken ~> 2.7.0

- files/default/handler/audit_report.rb
- libraries/helper.rb
Fixes https://github.com/chef-cookbooks/audit/issues/368
> Make entity_uuid work for Chef Infra 15

- README.md
Signed-off-by: Sean Horn <sean_horn@chef.io>
Point out to Chefs that Chef Client version 15.x requires a recent audit cookbook version. 7.3.0 is too old and fails with `Audit mode is enabled`.
Nope, Audit mode doesn't even exist in Chef Client 15.x. It was removed.
> Add additional audit cookbook matrix conditions around chef-client 15.x

- .travis.yml
- libraries/helper.rb
- libraries/reporters/cs_automate.rb
- resources/inspec_gem.rb
- spec/data/mock.rb
- spec/unit/libraries/automate_spec.rb
- spec/unit/libraries/cs_automate_spec.rb
- spec/unit/recipes/default_spec.rb
- spec/unit/report/audit_report_spec.rb
- spec/unit/report/fetcher_spec.rb
Adding back style, unit and chefspec testing in Travis after being accidentally removed in a previous PR.
> Restore style, unit and chefspec testing

- .rubocop.yml
- README.md
- attributes/default.rb
- files/default/handler/audit_report.rb
- libraries/helper.rb
- metadata.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
Introducing a new cookbook attribute `['audit']['attributes_save']` to remove `['audit']['attributes']` from the node object if needed.
Thank you @trickyearlobe for the feedback!
Opening the PR for now while working on tests
> Provide option to avoid saving the inspec attributes to the node object

- README.md
- attributes/default.rb
- metadata.rb
- resources/inspec_gem.rb
- spec/unit/libraries/helpers_spec.rb
The `default['audit']['inspec_version']` attribute has been added to the cookbook before chef-client came with an embedded InSpec gem.
Currently the `inspec_gem` resource of the `audit` cookbook is uninstalling the existing versions of InSpec and installing the one specified by the `inspec_version` attribute. With the release of Chef Infra Client 15, this breaks `/opt/chef/bin/chef-client` as can be seen here:
```
[root@myapache ~]# chef-client
Traceback (most recent call last):
3: from /usr/bin/chef-client:59:in `<main>'
2: from /opt/chef/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
1: from /opt/chef/embedded/lib/ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
/opt/chef/embedded/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find …
```
> Ignore inspec_version for chef client >= 15

- README.md
- files/default/handler/audit_report.rb
- libraries/reporters/audit-enforcer.rb
- metadata.rb
- spec/unit/libraries/audit_enforcer_spec.rb
This pull request implements an `audit enforcer` reporter to replace the `fail_if_any_audits_failed` feature that was removed a while ago.
> Implement an 'audit' reporter that will terminate Chef Client runs on profile failures

- files/default/handler/audit_report.rb
- libraries/reporters/audit-enforcer.rb
- metadata.rb
- spec/unit/libraries/audit_enforcer_spec.rb
Signed-off-by: Scott Babcock <scoba@hotmail.com>
Adding a custom exception to eliminate the need to set an attribute to propagate audit control failures.
> Add and check for custom exception to propagate audit failures

- README.md
- attributes/default.rb
- files/default/handler/audit_report.rb
- kitchen.dokken.yml
- test/cookbooks/test_helper/files/waivers-fixture/controls/waiver-check.rb
- test/cookbooks/test_helper/files/waivers-fixture/inspec.yml
- test/cookbooks/test_helper/files/waivers-fixture/waivers/waivers.yaml
- test/cookbooks/test_helper/recipes/setup_waiver_fixture.rb
- test/integration/waivers/default.rb
Adds an attribute that allows the user to specify a Waiver file.
A new kitchen-dokken test suite is provided, along with a test profile.
Note that at least the "inspec-attributes" suite was found to be broken at this time - no attempt was made to fix it on this PR, that's coming on another.
TESTING NOTE: 
The Audit cookbook should be tested with env vars:
```
KITCHEN_YAML=kitchen.dokken.yaml
CHEF_VERSION=15.6.10
```
A typical kitchen scenario might be `waivers-ubuntu-1804`.
Note that the waivers tests will **fail** unless the chef version is specified as above or higher, for the following chain of reasons:
- The audit cookbook, when running chef 15, ignores any requested InSpec version, and ALWAYS uses the gem version included with the Chef Infra Client.
- For chef 15, that appears to …
> Add waiver-file support

- libraries/helper.rb
In order to provide better user experince detect know errors 413 (`Request Entity Too Large`) & 413 (`Too Many Requests`) and append additional info. so that the user can easily track and perform adequate actions.
- 413:
```
You most likely hit the erchef request size in Chef Server that defaults to ~2MB. To increase this limit see audit cookbook TROUBLESHOOTING.md OR https://docs.chef.io/config_rb_server.html
```
- 429: 
```
This error typically means the data sent was larger than Automate's limit (4 MB). Run InSpec locally to identify any controls producing large diffs.
```
Fixes https://github.com/chef-cookbooks/audit/issues/384
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>
> Detect 429 & 413 and append an additional message

- .rubocop.yml
Signed-off-by: Jason Field <jason@avon-lea.co.uk>
Error: The `Style/BracesAroundHashParameters` cop has been removed.
> Error: The `Style/BracesAroundHashParameters` cop has been removed.

- .travis.yml
- TROUBLESHOOTING.md
- files/default/handler/audit_report.rb
- files/default/vendor/chef-server/fetcher.rb
- libraries/reporters/automate.rb
- libraries/reporters/cs_automate.rb
- spec/unit/libraries/audit_enforcer_spec.rb
- spec/unit/recipes/default_spec.rb
- test/cookbooks/test_helper/files/waivers-fixture/controls/waiver-check.rb
- The default Infra Server limit is 2mb as of 13.0
- Add a failiure to the cs_automate reporter on a nil uuid that matches the automate reporter
- Cookstyle fixes
> Update warnings on size limits, error on nil uuid

- attributes/default.rb
- files/default/handler/audit_report.rb
Add audit cookbook attributes support for the new InSpec options: `reporter_message_truncation` and `reporter_backtrace_inclusion `
Requires InSpec 4.18.114 or newer (bundled with Chef Infra Client starting with version 16.0.303 in the `current` release channel)
> Add audit cookbook attributes support for the new InSpec options

- .gitignore
- files/default/handler/audit_report.rb
- spec/unit/report/audit_report_spec.rb
Before this, InSpec exceptions caused by invalid profiles or invalid InSpec attributes that didn't produce a valid report were not being sent over to Automate / Chef-Server.
Catches any InSpec runtime exception and generates a minimal failed json report.
> Report even on inspec runtime exceptions

- README.md
Prefer and document usage of Chef Infra Client 15.x and above.
Chef Infra Client 14.x and earlier have been EOL for some time.
Signed-off-by: Sean Horn <sean_horn@chef.io>
> Updates for Chef Infra Client 15.x and above
