chef-cookbooks/audit

- .gitignore
- CONTRIBUTING.md
- LICENSE
- README.md
- TESTING.md
- chefignore
Syncing this cookbook up with our other community cookbooks
> Misc updates

- attributes/default.rb
- libraries/profile.rb
- metadata.rb
- recipes/default.rb
At the moment, the inspec_version is hardcoded and needs a cookbook update to pin to a different version.
> Make inspec_version a cookbook attribute and default it to latest

- libraries/profile.rb
- libraries/report.rb
- metadata.rb
Also removes the chef 13 warnings by adding nil type for optional properties
> Prevent null pointer when profile cannot be downloaded

- attributes/default.rb
- metadata.rb
> pin inspec to 0.20.1

- libraries/profile.rb
- libraries/report.rb
Changes handling of the token variable.
token was nil because of some resource handling
checked against Windows and Linux
> changed access token handling

- CHANGELOG.md
- Gemfile
- Rakefile
- metadata.rb
This PR add a Changelog to audit cookbook
> add changelog

- libraries/collector_classes.rb
> improve info logging to see which reporter is used

- examples/kitchen/.kitchen.linux.yml
- examples/kitchen/.kitchen.win.yml
- examples/kitchen/Gemfile
This PR fixes the broken examples. Since 0.14.0 we are using the new `collector` attribute that was not used in our examples.
> use new collector attribute in examples

- .travis.yml
This eliminates double-testing in travis
> restrict travis branch testing to master

- README.md
- attributes/default.rb
- examples/kitchen/.kitchen.linux.yml
- examples/kitchen/.kitchen.win.yml
- examples/kitchen/README.md
- libraries/helper.rb
- libraries/profile.rb
- libraries/report.rb
- recipes/default.rb
- spec/unit/recipes/default_spec.rb
This is rebase of #63. Thanks to @jeremymv2 for this great work. This fixes the refresh_token authentication which wasn't working correctly. It has been tested with ubuntu 14.04 and windows 2012R2
> Fix compliance direct communitcation

- .kitchen.yml
- Gemfile
- Rakefile
- libraries/collector_classes.rb
- libraries/helper.rb
- libraries/profile.rb
- libraries/report.rb
- metadata.rb
- recipes/default.rb
- travis.yml
Each change is in its own PR. Nothing too shocking here
> Minor fixes and changes

- attributes/default.rb
- recipes/default.rb
Attempting to make the experience a little more informative and easier to set up for first time users.
Based on some first hand experiences, I've seen new users struggle with how to correctly configure this cookbook.  This is just one attempt to make the path easier for them.
> adding clarifications

- resources/report.rb
> Fix resource_collection profiles selector. 

- README.md
- attributes/default.rb
Changed a few things as I'm writing the Compliance with Automate integration docs
> Audit docs improvements

- .github/PULL_REQUEST_TEMPLATE.md
Update the template for the DCO
> Update Github PR template

- README.md
> Supermarket

- README.md
We had neglected to include information about the new fetcher attribute in the readme!
This fixes that :)
@jerryaldrichiii
Signed-off-by: Victoria Jeffrey <vjeffrey@chef.io>
> Add fetcher info to readme

- README.md
Thanks @jerryaldrichiii for highlighting that issue.
> add reference to self-signed certs with visibility

- README.md
- attributes/default.rb
- files/default/handler/audit_report.rb
- libraries/collector_classes.rb
- metadata.rb
- spec/unit/report/audit_report_spec.rb
> Add chef-server-visibility collector

- .kitchen.yml
- attributes/default.rb
- libraries/compliance.rb
- recipes/default.rb
- recipes/inspec_package.rb
> Install inspec from source

- .kitchen.yml
- test/cookbooks/test_helper/recipes/install_inspec.rb
- test/integration/gem-install-version/default_spec.rb
Fix integration tests on Travis
> use inspec without nokogiri

- Gemfile
- metadata.rb
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
- Update metadata (```FC067: Ensure at least one platform supported in metadata: /home/travis/build/chef-cookbooks/audit/metadata.rb:1```)
- Update gem dependencies
> update metadata and gemfile

- files/default/handler/audit_report.rb
- libraries/helper.rb
Fixes reporting to Chef Compliance
> fix cc token and ensure we create a new string for a url

- spec/unit/libraries/json_file_spec.rb
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
follow-up PR to add a test for #246
> ensure json file outputs a json file

- README.md
> Add link to supported configs in README

- libraries/compliance.rb
- metadata.rb
> fix InSpec 1.27.0 Compliance::API use

- files/default/handler/audit_report.rb
- metadata.rb
Rebase of #236 with removal of version bump
> fix Reporter::ChefServer does not exist

- attributes/default.rb
Aligning the attributes file with the README
> Update comments in attributes file.

- .kitchen.yml
- .travis.yml
- Gemfile
- README.md
- spec/unit/libraries/cs_automate_spec.rb
- spec/unit/recipes/default_spec.rb
- spec/unit/recipes/upload_spec.rb
update travis and fauxhai configuration
> update travis configuration

- libraries/reporters/compliance.rb
brings back profile inheritance support for v4 and Chef Compliance
> support profile inheritance for Chef Compliance in audit cookbook 4

- README.md
> Fix inspec hosted profile diagram for Chef Supermarket

- README.md
Fixes https://github.com/chef-cookbooks/audit/issues/282
> let inspec set the default attribute for chef node attributes

- files/default/vendor/chef-server/fetcher.rb
As contributed https://github.com/chef-cookbooks/audit/pull/280
> simplify profile url code

- CHANGELOG.md
- metadata.rb
> Release v5.0.2

- files/default/handler/audit_report.rb
- libraries/reporters/automate.rb
- libraries/reporters/cs_automate.rb
- spec/data/mock.rb
- spec/unit/libraries/automate_spec.rb
- spec/unit/libraries/cs_automate_spec.rb
Needed in order to suggest and filter Automate reports by roles and cookbooks/recipes
> Enrich report with roles and recipes

- .github/CODEOWNERS
> Add CODEOWNERS for audit cookbook

- README.md
> README update for inspec_backend_cache feature

- .kitchen.yml
- .travis.yml
Travis needs some additional coaxing with rvm to properly update bundler.
> Fix bundler on Travis

- .kitchen.yml
- Gemfile
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
Pin to Chef 13 for now
> pin to chef 13

- CHANGELOG.md
- metadata.rb
> Bump Audit cookbook to 6.0.2

- CHANGELOG.md
- metadata.rb
> Release audit 7.0.1

- CHANGELOG.md
> add 7.1.0 release changelog

- CHANGELOG.md
- metadata.rb
> Bump version to 7.3.0 and update CHANGELOG

- README.md
There have been several fixes for both Inspec and the Audit cookbook to
support reporting to Automate v2.  This updates the support matrix to
indicate the minimum versions required to work with the latest Automate.
Specifically #334 and inspec/inspec#3401
Signed-off-by: Will Fisher <wfisher@chef.io>
None
> Update the automate support matrix

- .github/CODEOWNERS
- chefignore
- kitchen.vagrant.yml
Just a bit of syncing with how we do things in our other cookbooks. More to come
> Minor updates to kitchen, chefignore, and codeowners files

- .kitchen.yml
- .travis.yml
- resources/inspec_gem.rb
- test/cookbooks/test_helper/recipes/force_inspec_core.rb
- test/integration/chef15-compatible-inspec/default.rb
- test/integration/gem-install-core-version4/default.rb
The following changes are included in this PR
* Prevent downgrading Chef-InSpec < 4 when using Chef 15, 
* Handle installing/removing `inspec-core-bin` gem when appropriate
* Update the OS images used for testing and removes EOL ones.
Needed to handle the `inspec-core-bin` gem issue from #364
> Prevent downgrading to Chef-InSpec < 4 when using Chef 15

- attributes/default.rb
This is a necessary breaking change.  Major version must be bumped after
merging this.
> Change profiles default to a Hash

- README.md
Updating the README based on this PR from @jerryaldrichiii 
https://github.com/chef-cookbooks/audit/pull/358
> Remove deprecated examples using Array of Hashes

- files/default/vendor/chef-server/fetcher.rb
This function was removed in #383, likely because the original comment
on the function indicated that this was related to downloaded profiles
specifically from compliance.
In reality, this function overrides a function in the inspec Url
fetcher.  It overrides it so that it can use the Chef::ServerAPI
client. This client will use Chef Server's header based
authentication, allowing chef-clients to report audit data with a
specific data collector token.
Signed-off-by: Steven Danna <steve@chef.io>
> use Chef Server header auth in Chef Server fetcher

- .travis.yml
- metadata.rb
> Bump version and change travis os

- CHANGELOG.md
Signed-off-by: Alex Pop <apop@chef.io>
> Update changelog after release 9.1.0

- files/default/handler/audit_report.rb
- spec/unit/report/audit_report_spec.rb
Fixes https://github.com/chef-cookbooks/audit/issues/413
> Ignore missing waiver files

- CHANGELOG.md
- metadata.rb
Signed-off-by: Alex Pop <apop@chef.io>
> Release version 9.4.0

- README.md
Signed-off-by <sean_horn@chef.io>
Make note of the best configuration for Chef Infra Client 14. x clients
> Update for Chef Infra Client 14.x usage
